#!/bin/bash

#Data collection
#Getting list from file
#Creating file for each calls
#Collecting a single file
touch output
touch ind
echo "" > output
lttng create 1
lttng enable-event -a -k
lttng start
i=1
while [ true ]
do
    #echo "Hello world"
   
    #lttng start session, start logging
    
    #wait for a sec
    #here use the output of previous logs
    sleep 1
    echo "" > ind
    cat list | while read LINE
    do
        cat output | grep "$LINE" > test1
        cat test1 | wc -l >> ind
    done
    i=$((1-i))
    lttng create $i
    lttng enable-event -a -k
    lttng start
    lttng stop $((1-i))
    lttng view > output
    lttng destroy $((1-i))
    #stop log,stop session
done
